set(VTK_DIR "c:/csd/git_clone/D3DVideo_2/3rdParty/vtk-8.1")
set(PLATFORM "Win64")
set(VTK_VERSION           8.1)
set(VTK_LIB   
    vtkChartsCore-${VTK_VERSION}
	vtkCommonColor-${VTK_VERSION}
	vtkCommonComputationalGeometry-${VTK_VERSION}
	vtkCommonCore-${VTK_VERSION}
	vtkCommonDataModel-${VTK_VERSION}
	vtkCommonExecutionModel-${VTK_VERSION}
	vtkCommonMath-${VTK_VERSION}
	vtkCommonMisc-${VTK_VERSION}
	vtkCommonSystem-${VTK_VERSION}
	vtkCommonTransforms-${VTK_VERSION}
	vtkDICOMParser-${VTK_VERSION}
	#vtkdoubleconversion-${VTK_VERSION}
	vtkexpat-${VTK_VERSION}
	vtkFiltersAMR-${VTK_VERSION}
	vtkFiltersCore-${VTK_VERSION}
	vtkFiltersExtraction-${VTK_VERSION}
	vtkFiltersFlowPaths-${VTK_VERSION}
	vtkFiltersGeneral-${VTK_VERSION}
	vtkFiltersGeneric-${VTK_VERSION}
	vtkFiltersGeometry-${VTK_VERSION}
	vtkFiltersHybrid-${VTK_VERSION}
	vtkFiltersHyperTree-${VTK_VERSION}
	vtkFiltersImaging-${VTK_VERSION}
	vtkFiltersModeling-${VTK_VERSION}
	vtkFiltersParallel-${VTK_VERSION}
	vtkFiltersParallelImaging-${VTK_VERSION}
	vtkFiltersPoints-${VTK_VERSION}
	vtkFiltersProgrammable-${VTK_VERSION}
	vtkFiltersSelection-${VTK_VERSION}
	vtkFiltersSMP-${VTK_VERSION}
	vtkFiltersSources-${VTK_VERSION}
	vtkFiltersStatistics-${VTK_VERSION}
	vtkFiltersTexture-${VTK_VERSION}
	vtkFiltersVerdict-${VTK_VERSION}
	vtkfreetype-${VTK_VERSION}
	vtkGeovisCore-${VTK_VERSION}
	vtkgl2ps-${VTK_VERSION}
	#vtkglew-${VTK_VERSION}
	#vtkGUISupportQt-${VTK_VERSION}
	#vtkGUISupportQtSQL-${VTK_VERSION}
	vtkhdf5-${VTK_VERSION}
	vtkhdf5_hl-${VTK_VERSION}
	vtkImagingColor-${VTK_VERSION}
	vtkImagingCore-${VTK_VERSION}
	vtkImagingFourier-${VTK_VERSION}
	vtkImagingGeneral-${VTK_VERSION}
	vtkImagingHybrid-${VTK_VERSION}
	vtkImagingMath-${VTK_VERSION}
	vtkImagingMorphological-${VTK_VERSION}
	vtkImagingSources-${VTK_VERSION}
	vtkImagingStatistics-${VTK_VERSION}
	vtkImagingStencil-${VTK_VERSION}
	vtkInfovisCore-${VTK_VERSION}
	vtkInfovisLayout-${VTK_VERSION}
	vtkInteractionImage-${VTK_VERSION}
	vtkInteractionStyle-${VTK_VERSION}
	vtkInteractionWidgets-${VTK_VERSION}
	vtkIOAMR-${VTK_VERSION}
	vtkIOCore-${VTK_VERSION}
	vtkIOEnSight-${VTK_VERSION}
	vtkIOExodus-${VTK_VERSION}
	vtkIOExport-${VTK_VERSION}
	vtkIOGeometry-${VTK_VERSION}
	vtkIOImage-${VTK_VERSION}
	vtkIOImport-${VTK_VERSION}
	vtkIOInfovis-${VTK_VERSION}
	vtkIOLegacy-${VTK_VERSION}
	vtkIOLSDyna-${VTK_VERSION}
	vtkIOMINC-${VTK_VERSION}
	vtkIOMovie-${VTK_VERSION}
	vtkIONetCDF-${VTK_VERSION}
	vtkIOParallel-${VTK_VERSION}
	vtkIOParallelXML-${VTK_VERSION}
	vtkIOPLY-${VTK_VERSION}
	vtkIOSQL-${VTK_VERSION}
	vtkIOTecplotTable-${VTK_VERSION}
	vtkIOVideo-${VTK_VERSION}
	vtkIOXML-${VTK_VERSION}
	vtkIOXMLParser-${VTK_VERSION}
	vtkjpeg-${VTK_VERSION}
	vtklibxml2-${VTK_VERSION}
	vtklz4-${VTK_VERSION}
	#vtklzma-${VTK_VERSION}
	vtkParallelCore-${VTK_VERSION}
	vtkpng-${VTK_VERSION}
	vtkRenderingAnnotation-${VTK_VERSION}
	vtkRenderingContext2D-${VTK_VERSION}
	vtkRenderingContextOpenGL-${VTK_VERSION}
	vtkRenderingCore-${VTK_VERSION}
	#vtkRenderingExternal-${VTK_VERSION}
	vtkRenderingFreeType-${VTK_VERSION}
	#vtkRenderingGLPSOPENGL-${VTK_VERSION}
	vtkRenderingImage-${VTK_VERSION}
	vtkRenderingLabel-${VTK_VERSION}
	vtkRenderingLOD-${VTK_VERSION}
	vtkRenderingOPENGL-${VTK_VERSION}
	#vtkRenderingQt-${VTK_VERSION}
	vtkRenderingVolume-${VTK_VERSION}
	vtkRenderingVolumeOPENGL-${VTK_VERSION}
	vtksys-${VTK_VERSION}
	vtktiff-${VTK_VERSION}
	vtkverdict-${VTK_VERSION}
	vtkViewsContext2D-${VTK_VERSION}
	vtkViewsCore-${VTK_VERSION}
	vtkViewsInfovis-${VTK_VERSION}
	#vtkViewsQt-${VTK_VERSION}
	vtkzlib-${VTK_VERSION}
	opengl32
	)
	
#set(VTK_BIN_DIR    ${VTK_DIR}/bin/${PLATFORM})
set(VTK_LIB_DIR ${VTK_DIR}/lib/${PLATFORM})
message("${VTK_LIB_DIR}")

include_directories(${VTK_DIR}/include)
link_directories(${VTK_LIB_DIR})

